language: haskell
ghc:
- '7.8'
- '7.6'
- '7.4'
- '7.0'
script:
- cabal configure --enable-library-coverage --enable-tests
- cabal build
- cabal test
after_script:
- cabal install hpc-coveralls
- hpc-coveralls test
