name: flow
version: 1.0.10

category: Combinators, Functions, Utility
description: Flow provides operators for writing more understandable Haskell.
extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
github: tfausak/flow
license: MIT
maintainer: Taylor Fausak
synopsis: Write more understandable Haskell.

dependencies: base < 5
ghc-options: -Wall

library:
  exposed-modules: Flow

tests:
  test:
    dependencies:
      - doctest >= 0.9 && < 0.14
      - flow
      - QuickCheck == 2.*
      - template-haskell == 2.*
    main: FlowTest.hs
