name: flow
version: 1.0.20

category: Combinators, Functions, Utility
description: Flow provides operators for writing more understandable Haskell.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/flow
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Write more understandable Haskell.

dependencies:
  base: '>= 4.9.0 && < 4.15'
ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-safe
  -Wno-unsafe

library:
  source-dirs: library

tests:
  test:
    dependencies:
      doctest: '>= 0.11.0 && < 0.17'
      flow: -any
      QuickCheck: '>= 2.8.2 && < 2.15'
      template-haskell: '>= 2.11.0 && < 2.17'
    main: Main.hs
    source-dirs: tests
